import { createServer } from 'node:http';
import { FactoryApplication } from '../../../packages/application/src/factory.js';
import { MemoryBuildRepository } from '../../../packages/persistence/src/memory.js';
import { catalog } from '../../../packages/assets/src/catalog.js';
const app=new FactoryApplication({repository:new MemoryBuildRepository(),catalog});
function json(res,status,body){res.writeHead(status,{'content-type':'application/json; charset=utf-8'});res.end(JSON.stringify(body));}
async function body(req){let raw='';for await(const chunk of req)raw+=chunk;return raw?JSON.parse(raw):{};}
function errorResponse(e){return {code:e.message.startsWith('BUILD_')||e.message.startsWith('INVALID_')?'VALIDATION_ERROR':'INTERNAL_ERROR',message:e.message};}
const server=createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost'),p=url.pathname.split('/').filter(Boolean);if(req.method==='GET'&&url.pathname==='/health')return json(res,200,{status:'ok',service:'bsf-factory-api'});if(req.method==='GET'&&url.pathname==='/api/systems')return json(res,200,{data:app.catalog.listSystems()});if(req.method==='GET'&&url.pathname==='/api/modules')return json(res,200,{data:app.catalog.listModules()});if(req.method==='GET'&&url.pathname==='/api/builds')return json(res,200,{data:app.list()});if(req.method==='POST'&&url.pathname==='/api/builds')return json(res,201,{data:app.create(await body(req))});if(p[0]==='api'&&p[1]==='builds'&&p[2]){const id=p[2];if(req.method==='GET'&&p.length===3)return json(res,200,{data:app.get(id)});if(req.method==='POST'&&p[3]==='define')return json(res,200,{data:app.define(id,await body(req))});if(req.method==='POST'&&p[3]==='compose')return json(res,200,app.compose(id,(await body(req)).moduleIds??[]));if(req.method==='POST'&&p[3]==='configure')return json(res,200,app.configure(id,(await body(req)).configuration??{}));if(req.method==='POST'&&p[3]==='connect'){const b=await body(req);return json(res,200,app.connect(id,b.key,b.connection));}if(req.method==='POST'&&p[3]==='validate')return json(res,200,app.validate(id));if(req.method==='POST'&&p[3]==='deploy')return json(res,200,{data:app.prepareDeployment(id,(await body(req)).target??'export')});}return json(res,404,{error:{code:'NOT_FOUND',message:'Route not found'}});}catch(e){const status=e.message==='BUILD_NOT_FOUND'?404:e.message.startsWith('BUILD_')||e.message.startsWith('INVALID_')?400:500;return json(res,status,{error:errorResponse(e)});}});
const port=Number(process.env.PORT??3000);if(process.env.NODE_ENV!=='test')server.listen(port,()=>console.log(`BSF Factory API listening on ${port}`));export{server,app};
